version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app/
      - /app/node_modules/
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=task_manager
      - POSTGRES_PASSWORD=app

volumes:
  db: